whitelist_rules:
  - trailing_whitespace
  - trailing_semicolon
  - colon
  - comma
  - control_statement
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - MyBusTests